#!/bin/bash
./Executables/Serial a;
./Executables/Serial aa;
./Executables/Serial aaa;
./Executables/Serial aaaa;
./Executables/Serial aaaaa;
./Executables/Serial aaaaaa;
./Executables/Serial z;
./Executables/Serial zz;
./Executables/Serial zzz;
./Executables/Serial zzzz;
./Executables/Serial zzzzz;
./Executables/Serial zzzzzz;
./Executables/Serial p;
./Executables/Serial pp;
./Executables/Serial ppp;
./Executables/Serial pppp;
./Executables/Serial ppppp;
./Executables/Serial pppppp;
